name: deploy
  
on:


  push:
    branches:
      - dev
      - tst           
    paths:
      - '**/src/**'           
    
    
  workflow_dispatch:
    inputs:
      environment:
        type: choice        
        required: true
        default: 'dev'
        options: 
        - dev   
        - tst 
  
env:        
  # If its running on schedule deploys to PRD, otherwise goes to DEV
  environment: ${{ github.event.inputs.environment == '' && (github.event_name == 'dev' || 'tst') || github.event.inputs.environment }}
  workspace: ${{ github.event.inputs.workspace == '' && 'SalesSense' || github.event.inputs.workspace }}
  capacity: ${{ github.event.inputs.capacity || vars.FABRIC_CAPACITY }}
  admin_upns: ${{ github.event.inputs.admin_upns == '' && vars.FABRIC_ADMIN_UPNS || github.event.inputs.admin_upns }}  

jobs:

  deploy:    
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Fabric CLI
        run: |
          python -m pip install ms-fabric-cli

      - name: Run Deployment Script {Dev}        
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
        run: 
          python scripts/deploy.py --spn-auth --capacity $capacity --workspace $workspace --admin-upns $admin_upns
      
  refresh:    
      needs: [deploy]
      runs-on: ubuntu-latest

      steps:

        - name: Check out the code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"

        - name: Install Fabric CLI
          run: |
              python -m pip install ms-fabric-cli

        - name: Run Refresh Script
          env:
            FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
            FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
            FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
          run: |
            python scripts/refresh.py --spn-auth --environment $environment --config-file "./config.json"